fix: skip date validation when env variable not set
github/contributors pull request #144
Opened 2024-07-04 08:47 UTC by ReubenJ

# Pull Request

## Proposed Changes
Skip date validation when the respective environment variable is set. Currently, omitting the dates causes the action to fail, so it's impossible to output a report that does not include whether a user is a new contributor.

## Readiness Checklist

### Author/Contributor

- [x] If documentation is needed for this change, has that been included in this pull request
- [x] run `make lint` and fix any issues that you have introduced
- [x] run `make test` and ensure you have test coverage for the lines you are introducing
- [ ] If publishing new data to the public (scorecards, security scan results, code quality results, live dashboards, etc.), please request review from `@jeffrey-luszcz`

### Reviewer

- [ ] Label as either `bug`, `documentation`, `enhancement`, `infrastructure`, `maintenance` or `breaking`

2024-07-04 20:52 UTC, zkoppert requested changes
This is great! Thanks for adding!

I believe we also need to modify contributors.py where it has:

```python 
if start_date and end_date:
```

To have an else statement otherwise contributors will never be properly filled.

2024-07-04 20:53 UTC, zkoppert commented
> This is great! Thanks for adding!
> 
> I believe we also need to modify contributors.py where it has:
> 
> ```python 
> if start_date and end_date:
> ```
> 
> To have an else statement otherwise contributors will never be properly filled. 

Oops! Ok this just isn't true. Contributors is calculated before the conditional so never mind.

2024-07-04 20:54 UTC, zkoppert approved these changes

2024-07-04 20:54 UTC, merged

2024-07-05 07:39 UTC, ReubenJ commented
Yeah—one more test case for `contributors.py` probably wouldn't have hurt, but it does work with the fix! Thanks for the quick response.